plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/user/RedisStreams/retirement-planner/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/user/RedisStreams/retirement-planner"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]